language: node_js
node_js: node
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: pWNR/Eo1CEifaMuAQj0Vmlqd9tJBQ2aY5jTaaVt7OGHYEGwVCybUObb0WcfeqhVXZl6K6y+aF5VqbAz3ShuGcpeIvdVHM1wKn55Wa8WWS2yVvjomwUIFlihkTBVhLBhUWfT8ecTT5I23UJA+QQOPKIG4NAAdgcWJwJkGHPzXiwx6CPNTLH0m+7qNnA1zDKPRIXRMO8FJcwXfHfgC3ynBY+jr8kRVRxZjyDs4Y3mjGixFAGDPfc41DToZtHvYGWs3W+DNjBOXwXAvexdSyjWVwNDNs7xtn52NXozRA9vlWwa+Ef/IbZ3fs6TXAZtiY/qYvIqIncEURUK7yasF9X/zxXhMoJ6W56W1NyPFCaG4cjPlY79kWS2DhjruFw10TUnPu1p2dvaamiHnFa1CTb7RsISjsV+L1eT4eSaK8NZU13m6GHDEzlQsxs6aJhTbpemsWuQE8ddiwGiHo8nA6aMAKjuT9+jn/rk9uiVvwVUbHsmVAORfDyuCctRoBtZpvtCiJqrJ+S8sVzU14Dnk4DOnHixi+iQYeJc9Ai6E5JhrfYmP0hT+4oaC7W7xcL56SJ6BKvutxXPvaMLsJy/RZBMMQe4yCAmr6kGZvGFVYZfyFAZsIhQGugKkQb7ERBxs4YJcwKMgNU2LzqCJlPvh+yPyqJDLWf4/7qmgE2as0heNfVs=
  app: rhcptest
  on:
    repo: rockchalkwushock/migrating-file-structure
